/*
 *    MCreator note:
 *
 *    This file is autogenerated to connect all MCreator mod elements together.
 *
 */
package net.mcreator.djmusic;

import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.common.registry.EntityEntry;
import net.minecraftforge.fml.common.network.simpleimpl.IMessageHandler;
import net.minecraftforge.fml.common.network.simpleimpl.IMessage;
import net.minecraftforge.fml.common.network.IGuiHandler;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.fml.common.event.FMLServerStartingEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.discovery.ASMDataTable;
import net.minecraftforge.fml.common.IWorldGenerator;
import net.minecraftforge.fml.common.IFuelHandler;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.client.event.ModelRegistryEvent;

import net.minecraft.world.storage.WorldSavedData;
import net.minecraft.world.gen.IChunkGenerator;
import net.minecraft.world.chunk.IChunkProvider;
import net.minecraft.world.biome.Biome;
import net.minecraft.world.World;
import net.minecraft.util.ResourceLocation;
import net.minecraft.potion.Potion;
import net.minecraft.item.ItemStack;
import net.minecraft.item.Item;
import net.minecraft.entity.player.EntityPlayerMP;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.block.Block;

import java.util.function.Supplier;
import java.util.Random;
import java.util.Map;
import java.util.List;
import java.util.HashMap;
import java.util.Collections;
import java.util.ArrayList;

import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Retention;

public class ElementsDjMusicMod implements IFuelHandler, IWorldGenerator {
	public final List<ModElement> elements = new ArrayList<>();
	public final List<Supplier<Block>> blocks = new ArrayList<>();
	public final List<Supplier<Item>> items = new ArrayList<>();
	public final List<Supplier<Biome>> biomes = new ArrayList<>();
	public final List<Supplier<EntityEntry>> entities = new ArrayList<>();
	public final List<Supplier<Potion>> potions = new ArrayList<>();
	public static Map<ResourceLocation, net.minecraft.util.SoundEvent> sounds = new HashMap<>();
	public ElementsDjMusicMod() {
		sounds.put(new ResourceLocation("dj_music", "collaspe"), new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music", "collaspe")));
		sounds.put(new ResourceLocation("dj_music", "memory_bank"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music", "memory_bank")));
		sounds.put(new ResourceLocation("dj_music", "noisestorm"), new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music", "noisestorm")));
		sounds.put(new ResourceLocation("dj_music", "vairo_hide_and_seek"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music", "vairo_hide_and_seek")));
		sounds.put(new ResourceLocation("dj_music", "vairo_manchineel"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music", "vairo_manchineel")));
		sounds.put(new ResourceLocation("dj_music", "vairo_nightmare"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music", "vairo_nightmare")));
		sounds.put(new ResourceLocation("dj_music", "vairo_raindance"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music", "vairo_raindance")));
		sounds.put(new ResourceLocation("dj_music", "vairo_scarab"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music", "vairo_scarab")));
		sounds.put(new ResourceLocation("dj_music", "vairo_swara"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music", "vairo_swara")));
		sounds.put(new ResourceLocation("dj_music", "dream_mask_song"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music", "dream_mask_song")));
		sounds.put(new ResourceLocation("dj_music", "wither_heart"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music", "wither_heart")));
		sounds.put(new ResourceLocation("dj_music", "wishing_dead"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music", "wishing_dead")));
		sounds.put(new ResourceLocation("dj_music", "wings_of_salvation"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music", "wings_of_salvation")));
		sounds.put(new ResourceLocation("dj_music", "we_are_the_danger"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music", "we_are_the_danger")));
		sounds.put(new ResourceLocation("dj_music", "the_struggle"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music", "the_struggle")));
		sounds.put(new ResourceLocation("dj_music", "poison"), new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music", "poison")));
		sounds.put(new ResourceLocation("dj_music", "nightmares"), new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music", "nightmares")));
		sounds.put(new ResourceLocation("dj_music", "just_so_you_know"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music", "just_so_you_know")));
		sounds.put(new ResourceLocation("dj_music", "hard_pill_to_swallow"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music", "hard_pill_to_swallow")));
		sounds.put(new ResourceLocation("dj_music", "goodbye"), new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music", "goodbye")));
		sounds.put(new ResourceLocation("dj_music", "ender_wish"), new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music", "ender_wish")));
		sounds.put(new ResourceLocation("dj_music", "cold_as_ice"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music", "cold_as_ice")));
		sounds.put(new ResourceLocation("dj_music", "cold_as_ice_the_remake"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music", "cold_as_ice_the_remake")));
		sounds.put(new ResourceLocation("dj_music", "begin_again"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music", "begin_again")));
		sounds.put(new ResourceLocation("dj_music", "kind"), new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music", "kind")));
		sounds.put(new ResourceLocation("dj_music", "a_christmas_special"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music", "a_christmas_special")));
		sounds.put(new ResourceLocation("dj_music", "falling"), new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music", "falling")));
		sounds.put(new ResourceLocation("dj_music", "fractures"), new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music", "fractures")));
		sounds.put(new ResourceLocation("dj_music", "herobrines_revenge"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music", "herobrines_revenge")));
		sounds.put(new ResourceLocation("dj_music", "the_last_ender_watcher"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music", "the_last_ender_watcher")));
		sounds.put(new ResourceLocation("dj_music", "riseup"), new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music", "riseup")));
		sounds.put(new ResourceLocation("dj_music", "be_afraid"), new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music", "be_afraid")));
		sounds.put(new ResourceLocation("dj_music", "fed_up"), new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music", "fed_up")));
		sounds.put(new ResourceLocation("dj_music", "thefatrat_and_anjulie_close_to_the_sun"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music", "thefatrat_and_anjulie_close_to_the_sun")));
		sounds.put(new ResourceLocation("dj_music", "legends_never_die"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music", "legends_never_die")));
		sounds.put(new ResourceLocation("dj_music", "ellis-orbit"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music", "ellis-orbit")));
		sounds.put(new ResourceLocation("dj_music", "marshmello_alone"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music", "marshmello_alone")));
		sounds.put(new ResourceLocation("dj_music", "saviour_ft_haneri"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music", "saviour_ft_haneri")));
		sounds.put(new ResourceLocation("dj_music", "julius_dreisig_and_zeus_x_crona_invisible"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music", "julius_dreisig_and_zeus_x_crona_invisible")));
		sounds.put(new ResourceLocation("dj_music", "vicetone_nevada"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music", "vicetone_nevada")));
		sounds.put(new ResourceLocation("dj_music", "ping"), new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music", "ping")));
		sounds.put(new ResourceLocation("dj_music", "lying_2_me"), new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music", "lying_2_me")));
		sounds.put(new ResourceLocation("dj_music", "life_is_fun"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music", "life_is_fun")));
		sounds.put(new ResourceLocation("dj_music", "i_see_a_dreamer"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music", "i_see_a_dreamer")));
		sounds.put(new ResourceLocation("dj_music", "cartoon_on_and_on"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music", "cartoon_on_and_on")));
		sounds.put(new ResourceLocation("dj_music", "jett_sings_a_song"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music", "jett_sings_a_song")));
		sounds.put(new ResourceLocation("dj_music", "nivro_the_apocalypse"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music", "nivro_the_apocalypse")));
		sounds.put(new ResourceLocation("dj_music", "thefatrat_and_cecillia_gault"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music", "thefatrat_and_cecillia_gault")));
		sounds.put(new ResourceLocation("dj_music", "warriyo_mortals"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music", "warriyo_mortals")));
		sounds.put(new ResourceLocation("dj_music", "elektronomia_sky_high"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music", "elektronomia_sky_high")));
		sounds.put(new ResourceLocation("dj_music", "fnaf_song_sister_location_soulless"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music", "fnaf_song_sister_location_soulless")));
		sounds.put(new ResourceLocation("dj_music", "jpb_high"), new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music", "jpb_high")));
		sounds.put(new ResourceLocation("dj_music", "kdrew_circles"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music", "kdrew_circles")));
		sounds.put(new ResourceLocation("dj_music", "thefatrat_rise_up"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dj_music", "thefatrat_rise_up")));
	}

	public void preInit(FMLPreInitializationEvent event) {
		try {
			for (ASMDataTable.ASMData asmData : event.getAsmData().getAll(ModElement.Tag.class.getName())) {
				Class<?> clazz = Class.forName(asmData.getClassName());
				if (clazz.getSuperclass() == ElementsDjMusicMod.ModElement.class)
					elements.add((ElementsDjMusicMod.ModElement) clazz.getConstructor(this.getClass()).newInstance(this));
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
		Collections.sort(elements);
		elements.forEach(ElementsDjMusicMod.ModElement::initElements);
		this.addNetworkMessage(DjMusicModVariables.WorldSavedDataSyncMessageHandler.class, DjMusicModVariables.WorldSavedDataSyncMessage.class,
				Side.SERVER, Side.CLIENT);
	}

	public void registerSounds(RegistryEvent.Register<net.minecraft.util.SoundEvent> event) {
		for (Map.Entry<ResourceLocation, net.minecraft.util.SoundEvent> sound : sounds.entrySet())
			event.getRegistry().register(sound.getValue().setRegistryName(sound.getKey()));
	}

	@Override
	public void generate(Random random, int chunkX, int chunkZ, World world, IChunkGenerator cg, IChunkProvider cp) {
		elements.forEach(element -> element.generateWorld(random, chunkX * 16, chunkZ * 16, world, world.provider.getDimension(), cg, cp));
	}

	@Override
	public int getBurnTime(ItemStack fuel) {
		for (ModElement element : elements) {
			int ret = element.addFuel(fuel);
			if (ret != 0)
				return ret;
		}
		return 0;
	}

	@SubscribeEvent
	public void onPlayerLoggedIn(net.minecraftforge.fml.common.gameevent.PlayerEvent.PlayerLoggedInEvent event) {
		if (!event.player.world.isRemote) {
			WorldSavedData mapdata = DjMusicModVariables.MapVariables.get(event.player.world);
			WorldSavedData worlddata = DjMusicModVariables.WorldVariables.get(event.player.world);
			if (mapdata != null)
				DjMusicMod.PACKET_HANDLER.sendTo(new DjMusicModVariables.WorldSavedDataSyncMessage(0, mapdata), (EntityPlayerMP) event.player);
			if (worlddata != null)
				DjMusicMod.PACKET_HANDLER.sendTo(new DjMusicModVariables.WorldSavedDataSyncMessage(1, worlddata), (EntityPlayerMP) event.player);
		}
	}

	@SubscribeEvent
	public void onPlayerChangedDimension(net.minecraftforge.fml.common.gameevent.PlayerEvent.PlayerChangedDimensionEvent event) {
		if (!event.player.world.isRemote) {
			WorldSavedData worlddata = DjMusicModVariables.WorldVariables.get(event.player.world);
			if (worlddata != null)
				DjMusicMod.PACKET_HANDLER.sendTo(new DjMusicModVariables.WorldSavedDataSyncMessage(1, worlddata), (EntityPlayerMP) event.player);
		}
	}
	private int messageID = 0;
	public <T extends IMessage, V extends IMessage> void addNetworkMessage(Class<? extends IMessageHandler<T, V>> handler, Class<T> messageClass,
			Side... sides) {
		for (Side side : sides)
			DjMusicMod.PACKET_HANDLER.registerMessage(handler, messageClass, messageID, side);
		messageID++;
	}
	public static class GuiHandler implements IGuiHandler {
		@Override
		public Object getServerGuiElement(int id, EntityPlayer player, World world, int x, int y, int z) {
			return null;
		}

		@Override
		public Object getClientGuiElement(int id, EntityPlayer player, World world, int x, int y, int z) {
			return null;
		}
	}
	public List<ModElement> getElements() {
		return elements;
	}

	public List<Supplier<Block>> getBlocks() {
		return blocks;
	}

	public List<Supplier<Item>> getItems() {
		return items;
	}

	public List<Supplier<Biome>> getBiomes() {
		return biomes;
	}

	public List<Supplier<EntityEntry>> getEntities() {
		return entities;
	}

	public List<Supplier<Potion>> getPotions() {
		return potions;
	}
	public static class ModElement implements Comparable<ModElement> {
		@Retention(RetentionPolicy.RUNTIME)
		public @interface Tag {
		}
		protected final ElementsDjMusicMod elements;
		protected final int sortid;
		public ModElement(ElementsDjMusicMod elements, int sortid) {
			this.elements = elements;
			this.sortid = sortid;
		}

		public void initElements() {
		}

		public void init(FMLInitializationEvent event) {
		}

		public void preInit(FMLPreInitializationEvent event) {
		}

		public void generateWorld(Random random, int posX, int posZ, World world, int dimID, IChunkGenerator cg, IChunkProvider cp) {
		}

		public void serverLoad(FMLServerStartingEvent event) {
		}

		public void registerModels(ModelRegistryEvent event) {
		}

		public int addFuel(ItemStack fuel) {
			return 0;
		}

		@Override
		public int compareTo(ModElement other) {
			return this.sortid - other.sortid;
		}
	}
}
